apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: default
spec:
  selector:
    app: nodejs
  type: NodePort
  ports:
  - port: 3000 
    targetPort: 3000 
    nodePort: 30010